name: Plugin API
version: '${project.version}'
main: de.bacherik.pluginapi.Main
api-version: 1.18
authors: [ BachErik ]
description: This is a API that should make it easier to create Spigot plugins.
